import Controls from './controls';
import { CustomMedia, ElementItem, EventsList, MediaMethods, PlayerOptions, Source, Track } from './interfaces';
import Media from './media';
import Ads from './media/ads';
declare class Player {
    #private;
    static instances: {
        [id: string]: MediaMethods;
    };
    static customMedia: CustomMedia;
    static addMedia(name: string, mimeType: string, valid: (url: string) => string, media: Source): void;
    loader: HTMLSpanElement;
    playBtn: HTMLButtonElement;
    constructor(element: HTMLMediaElement | string, options?: PlayerOptions);
    init(): Promise<void>;
    load(): Promise<void>;
    play(): Promise<void>;
    pause(): void;
    stop(): void;
    destroy(): void;
    getContainer(): HTMLElement;
    getControls(): Controls;
    getCustomControls(): ElementItem[];
    getElement(): HTMLMediaElement;
    getEvents(): EventsList;
    getOptions(): PlayerOptions;
    activeElement(): Ads | Media;
    isMedia(): boolean;
    isAd(): boolean;
    getMedia(): Media;
    getAd(): Ads;
    addCaptions(args: Track): void;
    addControl(args: ElementItem): void;
    addElement(args: ElementItem): void;
    removeControl(controlName: string): void;
    prepareMedia(): Promise<void>;
    loadAd(src: string | string[]): Promise<void>;
    set src(media: Source[]);
    get src(): Source[];
    get id(): string;
    private _isValid;
    private _wrapInstance;
    private _createControls;
    private _generateID;
    private _createPlayButton;
    private _setEvents;
    private _autoplay;
    private _mergeOptions;
    private _enableKeyBindings;
}
export default Player;
